---
title: "Thrashing"
format: html
---

```{r}
rm(list = ls())
#import dataset and libraries needed
library(tidyverse)
library(readxl)
library(ggplot2)
library(ggsignif)
library(knitr)
library(broom)
thrashing <- read_excel("data/thrashing_assay.xlsx")

#view structure of each column
str(thrashing)
```

```{r}
#create per minute stat for each worm
thrash<- thrashing |>
  mutate(perMinute = ((trial1 + trial2 + trial3)/3)*2) |>
  mutate(treatment = recode(treatment,
                            "blue" = "Control",
                            "orange" = "Mannitol"))
```

```{r}
#create summary stats
summaryThrash<- thrash |>
  group_by(treatment, day) |>
  summarise(
    meanThrash = mean(perMinute),
    sdThrash = sd(perMinute)
  )
```

```{r}
#plot results
ggplot(summaryThrash, aes( x = day, y = meanThrash, fill = treatment)) +
  geom_col(position = position_dodge(width = 0.8)) +
 geom_signif(
   annotations = "*",
   y_position = 75,
   xmin = 1.8,
   xmax = 2.2,
   tip_length = 0.02
 )+
  scale_x_discrete(labels = c("D1"="D1",
                              "D2" = "D7",
                              "D3"= "D14")) +
   labs( title = "Thrashes between Treatments",
        x = "Day",
        y = "Mean Thrashes per Minute",
        fill = "Treatment")+
  scale_fill_manual(
    values = c("Control" = "turquoise",
              "Mannitol" = "turquoise4" )
  ) +
  theme_classic()
```

```{r}
#statistical test two way anova
anova_model <- aov(perMinute ~ treatment * day, data = thrash)
summary(anova_model)
#post hoc tukey HSD
tuk<-TukeyHSD(anova_model)
```

```{r}
#anova and tukey output tables
anovaTable <- tidy(anova_model)
kable(anovaTable,
      digits = 4,
      caption = "Two-way ANOVA Results for Thrashing Assay")

tukTidy<- tidy(tuk)

tuk_treatment_only <- tukTidy |>
  filter(
    str_detect(contrast, "Mannitol:D1-Control:D1") |
    str_detect(contrast, "Mannitol:D2-Control:D2") |
    str_detect(contrast, "Mannitol:D3-Control:D3")
  ) |>
  mutate(
    Day = case_when(
      str_detect(contrast, "D1") ~ "Day 1",
      str_detect(contrast, "D2") ~ "Day 2",
      str_detect(contrast, "D3") ~ "Day 3"
    ),
    contrast = "Mannitol vs Control"
  ) |>
  select(Day, contrast, estimate, conf.low, conf.high, adj.p.value)

kable(
  tuk_treatment_only,
  digits = 4,
  caption = "Tukey Post-hoc: Mannitol vs Control Within Each Day"
)

```
